src/SmartAdmin.Seed/Models/ManageViewModels/TopicViewModel.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SmartAdmin.Seed.Models.ManageViewModels
{
    public class TopicViewModel
    {
        public int ID { get; set; }
        public string TopicName { get; set; }
        public string Description { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string[] Keywords { get; set; }
        public string Status { get; set; }
        public bool isFeatured { get; set; }
        public string[] SelectedSources { get; set; }
    }
}

src/SmartAdmin.Seed/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SmartAdmin.Seed.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class TopicsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {

            return PartialView("_TopicData");
        }
    }
}

src/SmartAdmin.Seed/Views/Topics/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Bread crumb is created dynamically -->
<!-- row -->
<div class="row">

    <!-- col -->
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <h1 class="page-title txt-color-blueDark">
            <!-- PAGE HEADER -->
            <i class="fa-fw fa fa-file-text-o"></i>
            Quản lý chủ đề

        </h1>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 text-align-right">
        <div class="page-title">
            <a asp-action="Create" asp-controller="Topics" class="btn btn-success" data-toggle="modal" data-target="#remoteModal"><i class="fa fa-plus"></i> Tạo chủ đề mới</a>
        </div>
    </div>
    <!-- end col -->
    <!-- right side of the page with the sparkline graphs -->
    <!-- col -->
    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">

    </div>
    <!-- end col -->

</div>
<!-- end row -->
<!-- row -->
<div class="row">

    <div class="col-sm-12">

        <div class="well">

            <table class="table table-striped table-forum">
                <thead>
                    <tr>
                        <th colspan="2">Chủ đề</th>
                        <th class="text-center hidden-xs hidden-sm" style="width: 100px;">Bài viết</th>
                        <th class="hidden-xs hidden-sm" style="width: 200px;">Bài mới nhất</th>
                        <th class="hidden-xs hidden-sm" style="width: 50px;"></th>
                    </tr>
                </thead>
                <tbody>

                    <!-- TR -->
                    <tr class="warning">
                        <td class="text-center" style="width: 40px;">
                            <i class="fa fa-crosshairs fa-2x text-muted"></i>
                        </td>
                        <td>
                            <h4>
                                <a href="#ajax/forum-topic.html">
                                    Hello, welcome to SmartAdmin Forum!
                                </a>
                                <small><a href="#ajax/profile.html">John Doe</a> on <em>January 1, 2014</em></small>
                            </h4>
                        </td>

                        <td class="text-center hidden-xs hidden-sm">
                            <a href="javascript:void(0);">1342</a>
                        </td>
                        <td class="hidden-xs hidden-sm">
                            by
                            <a href="javascript:void(0);">John Doe</a>
                            <br>
                            <small>
                                <i>January 1, 2014</i>
                            </small>
                        </td>
                        <td class="hidden-xs hidden-sm text-center" style="width: 40px;">
                            <a href="javascript:void(0);"><i class="fa fa-cogs fa-2x"></i></a>
                        </td>
                    </tr>
                    <!-- end TR -->
                    <!-- TR -->
                    <tr>
                        <td class="text-center" style="width: 40px;">
                            <i class="fa fa-microphone fa-2x text-muted"></i>
                        </td>
                        <td>
                            <h4>
                                <a href="#ajax/forum-topic.html">
                                    News & Announcements
                                </a>
                                <small>Latest news and reports</small>
                            </h4>
                        </td>

                        <td class="text-center hidden-xs hidden-sm">
                            <a href="javascript:void(0);">1342</a>
                        </td>
                        <td class="hidden-xs hidden-sm">
                            by
                            <a href="javascript:void(0);">John Doe</a>
                            <br>
                            <small>
                                <i>January 1, 2014</i>
                            </small>
                        </td>
                        <td class="hidden-xs hidden-sm text-center" style="width: 40px;">
                            <a href="javascript:void(0);"><i class="fa fa-cogs fa-2x"></i></a>
                        </td>
                    </tr>
                    <!-- end TR -->
                    <!-- TR -->
                    <tr>
                        <td class="text-center" style="width: 40px;">
                            <i class="fa fa-pencil fa-2x text-muted"></i>
                        </td>
                        <td>
                            <h4>
                                <a href="#ajax/forum-topic.html">
                                    Forum Rules
                                </a>
                                <small>Please read carefully our forum rules before you post</small>
                            </h4>
                        </td>

                        <td class="text-center hidden-xs hidden-sm">
                            <a href="javascript:void(0);">1342</a>
                        </td>
                        <td class="hidden-xs hidden-sm">
                            by
                            <a href="javascript:void(0);">John Doe</a>
                            <br>
                            <small>
                                <i>January 1, 2014</i>
                            </small>
                        </td>
                        <td class="hidden-xs hidden-sm text-center" style="width: 40px;">
                            <a href="javascript:void(0);"><i class="fa fa-cogs fa-2x"></i></a>
                        </td>
                    </tr>
                    <!-- end TR -->

                </tbody>
            </table>
        </div>
    </div>

</div>

<!-- end row -->
<!-- row -->

<div class="row">

    <!-- a blank row to get started -->

</div>

<!-- end row -->
<!-- MODAL PLACE HOLDER -->
<div class="modal fade" id="remoteModal" tabindex="-1" role="dialog" aria-labelledby="remoteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
<!-- END MODAL -->
@section Scripts {
    <!-- SCRIPTS ON PAGE EVENT -->
    <script type="text/javascript">

        /* DO NOT REMOVE : GLOBAL FUNCTIONS!
     *
     * pageSetUp(); WILL CALL THE FOLLOWING FUNCTIONS
     *
     * // activate tooltips
     * $("[rel=tooltip]").tooltip();
     *
     * // activate popovers
     * $("[rel=popover]").popover();
     *
     * // activate popovers with hover states
     * $("[rel=popover-hover]").popover({ trigger: "hover" });
     *
     * // activate inline charts
     * runAllCharts();
     *
     * // setup widgets
     * setup_widgets_desktop();
     *
     * // run form elements
     * runAllForms();
     *
     ********************************
     *
     * pageSetUp() is needed whenever you load a page.
     * It initializes and checks for all basic elements of the page
     * and makes rendering easier.
     *
     */

        pageSetUp();


        // PAGE RELATED SCRIPTS

        // pagefunction

        var pagefunction = function () {


            var errorClass = 'invalid';
            var errorElement = 'em';



            var $registerForm = $("#smart-form").validate({
                errorClass: errorClass,
                errorElement: errorElement,
                highlight: function (element) {
                    $(element).parent().removeClass('state-success').addClass("state-error");
                    $(element).removeClass('valid');
                },
                unhighlight: function (element) {
                    $(element).parent().removeClass("state-error").addClass('state-success');
                    $(element).addClass('valid');
                },

                // Rules for form validation
                rules: {
                    username: {
                        required: true
                    },
                    email: {
                        required: true,
                        email: true
                    },
                    password: {
                        required: true,
                        minlength: 3,
                        maxlength: 20
                    },
                    passwordConfirm: {
                        required: true,
                        minlength: 3,
                        maxlength: 20,
                        equalTo: '#password'
                    },
                    firstname: {
                        required: true
                    },
                    lastname: {
                        required: true
                    },
                    gender: {
                        required: true
                    },
                    terms: {
                        required: true
                    }
                },

                // Messages for form validation
                messages: {
                    login: {
                        required: 'Please enter your login'
                    },
                    email: {
                        required: 'Please enter your email address',
                        email: 'Please enter a VALID email address'
                    },
                    password: {
                        required: 'Please enter your password'
                    },
                    passwordConfirm: {
                        required: 'Please enter your password one more time',
                        equalTo: 'Please enter the same password as above'
                    },
                    firstname: {
                        required: 'Please select your first name'
                    },
                    lastname: {
                        required: 'Please select your last name'
                    },
                    gender: {
                        required: 'Please select your gender'
                    },
                    terms: {
                        required: 'You must agree with Terms and Conditions'
                    }
                },

                // Do not change code below
                errorPlacement: function (error, element) {
                    error.insertAfter(element.parent());
                }
            });



            // START AND FINISH DATE
            $('#startdate').datepicker({
                dateFormat: 'dd/mm/yy',
                prevText: '<i class="fa fa-chevron-left"></i>',
                nextText: '<i class="fa fa-chevron-right"></i>',
                onSelect: function (selectedDate) {
                    $('#finishdate').datepicker('option', 'minDate', selectedDate);
                }
            });

            $('#finishdate').datepicker({
                dateFormat: 'dd/mm/yy',
                prevText: '<i class="fa fa-chevron-left"></i>',
                nextText: '<i class="fa fa-chevron-right"></i>',
                onSelect: function (selectedDate) {
                    $('#startdate').datepicker('option', 'maxDate', selectedDate);
                }
            });

            // Load form valisation dependency
            loadScript("/js/plugin/jquery-form/jquery-form.js", pagefunction);

            /*
             * TAGS
             */

            loadScript("/js/plugin/bootstrap-tags/bootstrap-tagsinput.min.js",
                function () {
                    $('.tagsinput').tagsinput('refresh');
                });

        };

        // end pagefunction
        // run pagefunction on load
        pagefunction();



    </script>
}

src/SmartAdmin.Seed/Views/Topics/_TopicData.cshtml
@{
    @using SmartAdmin.Seed.Models.ManageViewModels
    @model TopicViewModel
}
<article class="col-sm-12 col-md-12 col-lg-12">
    <div class="jarviswidget" id="wid-id-3" data-widget-editbutton="true" data-widget-custombutton="true" data-widget-deletebutton="true">
        <!-- widget options:
        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

        data-widget-colorbutton="false"
        data-widget-editbutton="false"
        data-widget-togglebutton="false"
        data-widget-deletebutton="false"
        data-widget-fullscreenbutton="false"
        data-widget-custombutton="false"
        data-widget-collapsed="true"
        data-widget-sortable="false"

        -->
        <header>
            <span class="widget-icon">
                <i class="fa fa-edit"></i>
            </span>
            @if (ViewData["Action"] == null)
            {
                <h2>Tạo mới chủ đề </h2>
            }
            else
            {
                <h2>Cấu hình chủ đề </h2>

            }


        </header>

        <!-- widget div-->
        <div>

            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->

            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body no-padding">

                <form action="" id="topic-form" class="smart-form" novalidate="novalidate">
                    <header>Thông tin chủ đề</header>
                    <fieldset>
                        <div class="row">
                            <section class="col col-lg-12">
                                <label class="label">Tên chủ đề</label>
                                <label class="input" asp-for="TopicName">
                                    <i class="icon-append fa fa-user"></i>
                                    <input asp-for="TopicName" type="text" name="name" placeholder="Nhập tên chủ đề">
                                </label>
                            </section>

                            <section class="col col-lg-12">
                                <label class="label">Mô tả chủ đề</label>
                                <label class="textarea">
                                    <i class="icon-append fa fa-comment"></i>
                                    <textarea rows="2" name="description" id="description" placeholder="Nhập mô tả chủ đề"></textarea>
                                </label>
                            </section>
                        </div>

                        <div class="row">
                            <section class="col col-6">
                                <label class="label">Ngày bắt đầu theo dõi</label>
                                <label class="input">
                                    <i class="icon-append fa fa-calendar"></i>
                                    <input type="text" name="startdate" id="startdate" placeholder="Ngày bắt đầu">
                                </label>
                            </section>
                            <section class="col col-6">
                                <label class="label">Ngày kết thúc theo dõi</label>
                                <label class="input">
                                    <i class="icon-append fa fa-calendar"></i>
                                    <input type="text" name="finishdate" id="finishdate" placeholder="Ngày kết thúc">
                                </label>
                            </section>
                        </div>
                    </fieldset>
                    <fieldset>
                        <div class="row">
                            <section class="col col-lg-12">
                                <label class="label">Danh sách từ khóa</label>
                                <input class="form-control tagsinput" value="" data-role="tagsinput" placeholder="Nhấn enter để thêm">
                            </section>

                        </div>
                        <div class="row">
                            <section class="col col-lg-12">
                                <label class="label">Chọn nguồn tin</label>
                                <div class="inline-group">
                                    <label class="checkbox">
                                        <input type="checkbox" name="checkbox-inline" checked="checked">
                                        <i></i>Báo mạng
                                    </label>
                                    <label class="checkbox">
                                        <input type="checkbox" name="checkbox-inline">
                                        <i></i>Diễn đàn
                                    </label>
                                    <label class="checkbox">
                                        <input type="checkbox" name="checkbox-inline">
                                        <i></i>Facebook
                                    </label>
                                    <label class="checkbox">
                                        <input type="checkbox" name="checkbox-inline">
                                        <i></i>Twitter
                                    </label>
                                </div>
                            </section>
                        </div>
                    </fieldset>
                    <fieldset>
                        <div class="row">

                            
                            <section class="col col-lg-12">

                                <div class="onoffswitch-container">
                                    <span class="onoffswitch-title">Chủ đề nổi bật</span>
                                    <span class="onoffswitch">
                                        <input type="checkbox" class="onoffswitch-checkbox" id="autoopen">
                                        <label class="onoffswitch-label" for="autoopen">
                                            <span class="onoffswitch-inner" data-swchon-text="BẬT" data-swchoff-text="TẮT"></span>
                                            <span class="onoffswitch-switch"></span>
                                        </label>
                                    </span>
                                </div>

                            </section>
                        </div>
                    </fieldset>

                    <footer>
                        <button type="submit" class="btn btn-primary">
                            Cập nhật
                        </button>
                    </footer>
                </form>

            </div>
            <!-- end widget content -->

        </div>
        <!-- end widget div -->

    </div>
</article>